name: spidr_cli
description: Command-line interface definitions and commands for SPIDR.
version: 0.0.1
resolution: workspace
homepage: https://github.com/rajarajanponraj/spidr
repository: https://github.com/rajarajanponraj/spidr/tree/main/packages/spidr_cli
issue_tracker: https://github.com/rajarajanponraj/spidr/issues

environment:
  sdk: ^3.12.0

dependencies:
  spidr_core: ^0.0.1
  args: ^2.4.2
  meta: ^1.10.0

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
